#
# generated by 'fips gen', don't edit, don't add to version control!
#
if (EXISTS "C:/dev/SKWS/fips-utils/fips-include.cmake")
    include("C:/dev/SKWS/fips-utils/fips-include.cmake")
elseif (EXISTS "C:/dev/SKWS/fips-utils/fips-files/include.cmake")
    include ("C:/dev/SKWS/fips-utils/fips-files/include.cmake")
endif()
if (EXISTS "C:/dev/SKWS/fips-utils/lib/${FIPS_PLATFORM_NAME}")
    link_directories("C:/dev/SKWS/fips-utils/lib/${FIPS_PLATFORM_NAME}")
endif()
